# Replace this with your API key from mcbouncer.com/apikey
apiKey: REPLACE
numBansDisallow: 10
showBanMessages: true
defaultBanMessage: 'Banned for rule violation.'
defaultKickMessage: 'Kicked by an admin.'
# To find out more about fastBans, see mcbouncer.com/performance
fastBans: false
