# Replace this with your API key from mcbouncer.com/apikey
apiKey: REPLACE

#Default messages used for banning and kicking
defaultBanMessage: 'Banned for rule violation.'
defaultKickMessage: 'Kicked by an admin.'
