name: MCBouncer
version: 1.0beta
author: MCBouncer Staff
website: http://www.mcbouncer.com/
main: com.mcbouncer.bukkit.MCBouncer
description: MCBouncer is a cloud-based ban suite and protection program that is modular, unbiased, and fair to its users.
commands:
  ban:
    description: 'Ban a username'
    usage: '/<command> [reason]'
    aliases: []
  unban:
    description: 'Unban a username'
    usage: '/<command> playername'
    aliases: []
  banip:
    description: 'Ban an IP'
    usage: '/<command> playername/IP'
    aliases: []
  unbanip:
    description: 'Unabn an IP'
    usage: '/<command> playername/IP'
    aliases: []
  lookup:
    description: 'See all bans by a username'
    usage: '/<command> playername'
    aliases: []
  kick:
    description: 'Kick a user from the server'
    usage: '/<command> playername [reason]'
    aliases: []
  mcbouncer:
    description: 'MCBouncer commands'
    usage: '/<command> [help|version|reload]'
    aliases: []