name: MCBouncer
version: 1.1beta
author: MCBouncer Staff
website: http://www.mcbouncer.com/
main: com.mcbouncer.bukkit.BukkitPlugin
description: MCBouncer is a cloud-based ban suite and protection program that is modular, unbiased, and fair to its users.
commands:
  ban:
    description: 'Ban a username'
    usage: '/<command> [reason]'
  unban:
    description: 'Unban a username'
    usage: '/<command> playername'
  banip:
    description: 'Ban an IP'
    usage: '/<command> playername/IP'
  unbanip:
    description: 'Unban an IP'
    usage: '/<command> playername/IP'
  lookup:
    description: 'See all bans by a username'
    usage: '/<command> playername'
  kick:
    description: 'Kick a user from the server'
    usage: '/<command> playername [reason]'
    aliases: ['boot']
  mcbouncer:
    description: 'MCBouncer commands'
    usage: '/<command> [help|version|reload]'
    aliases: ['mcb']
  addnote:
    description: 'Adds a note'
    usage: '/<command> playername note'
  removenote:
    description: 'Removes a note'
    usage: '/<command> noteid'
    aliases: ['delnote']
